package demo.test_web_drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

    static final long serialVersionUID = 1L;

    private String name;
    private Integer age;

    public Person()
    {
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public Integer getAge()
    {
        return this.age;
    }

    public void setAge(Integer age)
    {
        this.age = age;
    }

    public Person(String name, Integer age)
    {
        this.name = name;
        this.age = age;
    }

}
