package org.drools.rules.drools_rules;

import org.drools.rules.drools_rules.FormulasOptionVO;
import org.drools.rules.drools_rules.DoubleUtil;

// ERS MIN
global java.lang.Double ers_min;

// 汇率调整费
rule "ERS MIN"
    salience 59
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setItemTotal(ers_min);
end

rule "ERS"
    salience 58
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(6));
        Double itemTotal = DoubleUtil.mul($vo.getWeight(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "ERS-01"
    salience 57
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(6));
        Double itemTotal = DoubleUtil.mul($vo.getVolume(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "ERS-END"
    salience 55
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setTotal(DoubleUtil.add($vo.getTotal(), $vo.getItemTotal()));
end
