package org.drools.rules.drools_rules;

import org.drools.rules.drools_rules.FormulasOptionVO;
import org.drools.rules.drools_rules.DoubleUtil;

// LCL-SVC MIN
global java.lang.Double lcl_svc_min;

// 拆箱费
rule "LCL-SVC MIN"
    salience 89
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setItemTotal(lcl_svc_min);
end

rule "LCL-SVC"
    salience 88
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(30));
        Double itemTotal = DoubleUtil.mul($vo.getWeight(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "LCL-SVC-01"
    salience 87
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(15));
        Double itemTotal = DoubleUtil.mul($vo.getVolume(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "LCL-SVC-02"
    salience 86
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(15));
        Double itemTotal = DoubleUtil.mul($vo.getWeight(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end



rule "LCL-SVC-END"
    salience 85
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setTotal(DoubleUtil.add($vo.getTotal(), $vo.getItemTotal()));
end