package org.drools.rules.drools_rules;

import org.drools.rules.drools_rules.FormulasOptionVO;
import org.drools.rules.drools_rules.DoubleUtil;

// QURAY DUES MIN
global java.lang.Double quray_dues_min;

// 码头费
rule "QURAY DUES MIN"
    salience 100
    lock-on-active true
    agenda-group "001"
    when
        $vo : FormulasOptionVO()
    then
        $vo.setItemTotal(quray_dues_min);
end

rule "QURAY DUES"
    salience 99
    lock-on-active true
    agenda-group "001"
    when
        $vo : FormulasOptionVO(weight/number > 0.02 && volume/weight < 5)
    then
        $vo.setUnit_price(42.83);
        Double itemTotal = DoubleUtil.mul($vo.getWeight(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "QURAY DUES 01"
    salience 98
    lock-on-active true
    agenda-group "001"
    when
        $vo : FormulasOptionVO(weight/number < 0.02 && volume/weight < 5)
    then
        $vo.setUnit_price(53.49);
        Double itemTotal = DoubleUtil.mul($vo.getWeight(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "QURAY DUES 02"
    salience 97
    lock-on-active true
    agenda-group "001"
    when
        $vo : FormulasOptionVO(volume/weight > 5)
    then
        $vo.setUnit_price(8.58);
        Double itemTotal = DoubleUtil.mul($vo.getVolume(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "QURAY DUES END"
    salience 96
    lock-on-active true
    agenda-group "001"
    when
        $vo : FormulasOptionVO()
    then
        $vo.setTotal(DoubleUtil.add($vo.getTotal(), $vo.getItemTotal()));
end