package org.drools.rules.drools_rules;

import org.drools.rules.drools_rules.FormulasOptionVO;
import org.drools.rules.drools_rules.DoubleUtil;

// CISF MIN
global java.lang.Double cisf_min;

// 进口附加费
rule "CISF MIN"
    salience 39
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setItemTotal(cisf_min);
end

rule "CISF"
    salience 38
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(50));
        Double itemTotal = DoubleUtil.mul($vo.getWeight(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "CISF-01"
    salience 37
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setUnit_price(Double.valueOf(50));
        Double itemTotal = DoubleUtil.mul($vo.getVolume(), $vo.getUnit_price());
        if (itemTotal > $vo.getItemTotal()) {
            $vo.setItemTotal(itemTotal);
        }
end

rule "CISF-END"
    salience 36
    lock-on-active true
    when
        $vo : FormulasOptionVO()
    then
        $vo.setTotal(DoubleUtil.add($vo.getTotal(), $vo.getItemTotal()));
end