package drools.rules.sample;
//dialect  "mvel"

import org.drools.spring.demo.simple.Message;

rule "demo2"
    when
        eval(true);
    then
        System.out.println("Hello ChenFeng!");
end

rule "demo3"
    salience 1
    when
        Message( status == Message.GOODBYE);
    then
        System.out.println("Goodbay ChenFeng ChenFeng!");
end

rule "demo4"
    salience -1
    when
        Message( status == Message.HELLO);
    then
        System.out.println("Hello ChenFeng ChenFeng!");
end

